# Generated by Django 4.0.1 on 2022-01-22 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(default=None, max_length=45, null=True)),
                ('adresa', models.CharField(default=None, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sucursale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(default=None, max_length=45, null=True)),
                ('localitate', models.CharField(default=None, max_length=45, null=True)),
                ('cartier', models.CharField(default=None, max_length=45, null=True)),
                ('datadeschidere', models.DateField(default=None, null=True)),
                ('banca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Banca.banci')),
            ],
        ),
        migrations.CreateModel(
            name='Angajati',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(default=None, max_length=45, null=True)),
                ('prenume', models.CharField(default=None, max_length=45, null=True)),
                ('adresa', models.CharField(default=None, max_length=45, null=True)),
                ('functie', models.CharField(default=None, max_length=45, null=True)),
                ('salariu', models.FloatField(default=None, null=True)),
                ('banca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Banca.banci')),
            ],
        ),
    ]
